export const CABINET_USERS_REQUEST = 'CABINET_USERS_REQUEST';
export const CABINET_USERS_SUCCESS = 'CABINER_USERS_SUCCESS';
export const CABINET_USERS_FAIL    = 'CABINER_USERS_FAIL';
export const SET_CABINET_USERS     = 'SET_CABINET_USERS';
