export const FETCH_ALL_NEWS = 'FETCH_ALL_NEWS';
export const FETCH_NEWS = 'FETCH_NEWS';
export const SET_NEWS = 'SET_NEWS';
export const SET_ACTIVE_NEWS = 'SET_ACTIVE_NEWS';

export const FETCH_CABINET_NEWS = 'FETCH_CABINET_NEWS';
export const FETCH_CABINET_NEWS_FAIL = 'FETCH_CABINET_NEWS_FAIL';
export const SET_CABINET_NEWS = 'SET_CABINET_NEWS';

export const CREATE_NEWS_VALIDATION = 'CREATE_NEWS_VALIDATION';
export const CREATE_NEWS_REQUEST = 'CREATE_NEWS_REQUEST';
