export const VALIDATE_NEW_NAME = 'VALIDATE_NEW_NAME';
export const VALIDATE_NEW_EMAIL = 'VALIDATE_NEW_EMAIL';
export const VALIDATE_NEW_PASSWORD = 'VALIDATE_NEW_PASSWORD';

export const REQUEST_SETTINGS_ACCOUNT_DATA = 'REQUEST_SETTINGS_ACCOUNT_DATA';
export const NEW_NAME_SUCCESS = 'NEW_NAME_SUCCESS';
export const NEW_NAME_FAIL = 'NEW_NAME_FAIL';
export const CHANGE_NAME = 'CHANGE_NAME';
