export const VALIDATE_NEW_NAME = 'VALIDATE_NEW_NAME';
export const VALIDATE_NEW_EMAIL = 'VALIDATE_NEW_EMAIL';
export const VALIDATE_NEW_PASSWORD = 'VALIDATE_NEW_PASSWORD';

export const REQUEST_SETTINGS_ACCOUNT_DATA = 'REQUEST_SETTINGS_ACCOUNT_DATA';
export const SETTINGS_ACCOUNT_SUCCESS = 'SETTINGS_ACCOUNT_SUCCESS';
export const SETTINGS_ACCOUNT_FAIL = 'SETTINGS_ACCOUNT_FAIL';
