export const VALIDATE_NEW_NAME = 'VALIDATE_NEW_NAME';
export const REQUEST_NEW_NAME = 'REQUEST_NEW_NAME';
export const SUCCESS_NEW_NAME = 'SUCCESS_NEW_NAME';
export const FAIL_NEW_NAME = 'FAIL_NEW_NAME';

export const VALIDATE_NEW_EMAIL = 'VALIDATE_NEW_EMAIL';
export const REQUEST_NEW_EMAIL = 'REQUEST_NEW_EMAIL';
export const SUCCESS_NEW_EMAIL = 'SUCCESS_NEW_EMAIL';
export const FAIL_NEW_EMAIL = 'FAIL_NEW_EMAIL';

export const VALIDATE_NEW_PASSWORD = 'VALIDATE_NEW_PASSWORD';
