export const FETCH_ALL_INCIDENTS = 'FETCH_ALL_INCIDENTS';
export const FETCH_INCIDENT = 'FETCH_INCIDENT';
export const SET_LOADING = 'SET_LOADING';
export const SET_ERROR = 'SET_ERROR';
export const SET_INCIDENTS = 'SET_INCIDENTS';
