export const SET_CITIES = 'SET_CITIES';
export const SET_CITY_ERROR = 'SET_CITY_ERROR';
export const SET_CITIES_LOADING = 'SET_CITIES_LOADING';

export const TOGGLE_CITIES_SELECTOR = 'TOGGLE_CITIES_SELECTOR';
export const CHANGE_CITY = 'CHANGE_CITY';
export const CHANGE_SELECTED_CITY_ID = 'CHANGE_SELECTED_CITY_ID';

export const FETCH_CITIES = 'FETCH_CITIES';
export const FETCH_CITIES_SUCCESS = 'FETCH_CITIES_SUCCESS';
export const FETCH_CITIES_FAIL = 'FETCH_CITIES_FAIL';
